### ISSUE TITLE
Investigate/fix mass failures against www-dev.allizom.org (family/Tabzilla)

### ISSUE THREAD

**Issue by stephendonner** [mozilla/mcom-tests#397]
We've got a metric ton of failures [1] against www-dev.allizom.org, likely due to https://github.com/mozilla/bedrock/commit/6eefdec1bcd8fe6b02c453b6292ebce06d8ccb60 (/cc @jpetto & @craigcook for expertise help!) - can you two help us sort this out with PRs (pending and/or merged is OK)

Thanks!

I'm not sure when we're merging, but hopefully with our page-object model, this (should) be easily fixed/fixable?

Also cc:ing @bobsilverberg + @davehunt from our side

[1] https://webqa-ci.mozilla.com/view/Mozilla.org/job/mozilla.org.dev.saucelabs/1054/

**Comment by craigcook** [comment]
That commit removed the old /products page and changes all the various places that linked to it, now pointing to /firefox/products, hence all these failures on specific link URLs (as in tabzilla, the about page, breadcrumbs, etc). I think we just need to go down the list and update all those tests to point to the new URL. And some of those tests can be removed entirely, namely all the 'TestProductPage' ones.

Note also that this will be somewhat temporary, since we're redesigning most of the current "about Mozilla" content in the next few months. There will almost certainly be a whole new page at mozilla.org/products, but that's a ways down the road. We'll want to make sure QA is involved in that redesign because it'll be lots of changes on a lot of older pages, guaranteed to need lots of updates to test automation.

**Comment by stephendonner** [comment]
Thx, @craigcook - can you take a (few) rough cuts at "fixing" this?  Due to our page-object model, it *should* be easy to do so - and the two I've cc:ed from my team should be able to help, tonight/early morning, as well.

**Comment by stephendonner** [comment]
Craig fixed this in https://github.com/mozilla/mcom-tests/pull/398, 1st try, I should add!
